/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design;

import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Analisa;
import model.CountData;
import model.LoadTable;
import model.TestConnection;

/**
 *
 * @author rachmad
 */
public class FormAnalisa extends javax.swing.JFrame {
    private LoadTable tb1, tb2, hasilKriteriaTable;
    private TestConnection tc;
    private FormAnalisaMobil analisaMobil;
    private DefaultTableModel tm1, tm2, tm3, tm4, tm5, hasilKriteriaTableModel;
    private String lowBobot, highBobot;
    private Analisa analisa;
    /**
     * Creates new form Analisa
     */
    public FormAnalisa() {
        analisa = new Analisa();
        tc = new TestConnection();
        
        analisaMobil = new FormAnalisaMobil();
        tm1 = analisa.getTableModel1();
        tm2 = analisa.getTableModel2();
        tm3 = analisa.getTableModel3();
        tm4 = analisaMobil.getTableModel();
        
        /*
         * final perhitungan smart
        */
        hasilKriteriaTable = new LoadTable(tc.getConnection(), "select * from hasil_analisa");
        hasilKriteriaTableModel = hasilKriteriaTable.getTableModel();
        Object[] column = {"id_mobil", "nama_model", "hasil"};
        tm5 = new DefaultTableModel(column, 0);
        for(int i=0; i<hasilKriteriaTableModel.getRowCount(); i++){
            int result = 0;
            List row = new ArrayList();
            for(int j=0; j<hasilKriteriaTableModel.getColumnCount(); j++){
                if(j>1){
                    double val1 = Double.parseDouble(hasilKriteriaTableModel.getValueAt(i, j).toString());
                    double val2 = Double.parseDouble(tm3.getValueAt(j-2, 4).toString());
                    result += (val1 * val2);
                }
                else{
                    String vector = hasilKriteriaTableModel.getValueAt(i, j).toString();
                    System.out.println(i + " - " + j + " = " + vector);
                    row.add(vector);
                }
            }
            row.add(Double.toString(result));
            Object[] addRow = new Object[row.size()];
            addRow = row.toArray();
            tm5.addRow(addRow);
            //tm5.setValueAt(Double.toString(result), i, 2);
        }
        
        initComponents();
        
        jTable1.setDefaultRenderer(Object.class, new LastRowBold());
        jTable2.setDefaultRenderer(Object.class, new LastRowBold());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        carAnalize = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(tm1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(tm2);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("ANALISA BOBOT PALING TIDAK PENTING");

        jLabel2.setText("ANALISA BOBOT PALING PENTING");

        jLabel3.setText("ANALISA RATA-RATA BOBOT");

        jTable3.setModel(tm3);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(10);
        jScrollPane3.setViewportView(jTable3);

        carAnalize.setText("Go To Car Analize");
        carAnalize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carAnalizeActionPerformed(evt);
            }
        });

        jTable4.setModel(tm5);
        jScrollPane4.setViewportView(jTable4);

        jLabel4.setText("PERHITUNGAN TOTAL UTILITY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carAnalize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                                .addComponent(jScrollPane4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carAnalize, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carAnalizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carAnalizeActionPerformed
        new FormAnalisaMobil().setVisible(true);
    }//GEN-LAST:event_carAnalizeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAnalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAnalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAnalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAnalisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAnalisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton carAnalize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}

class LastRowBold extends DefaultTableCellRenderer {
   public Component getTableCellRendererComponent(JTable table, 
   Object value, boolean isSelected, boolean hasFocus, int row, int column) {
     JLabel parent = (JLabel) super.getTableCellRendererComponent(table, 
      value, isSelected, hasFocus, row, column);
     if(row == table.getRowCount()-1) parent.setFont(
       parent.getFont().deriveFont(Font.BOLD));
     return parent;
   }    
}