/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design.panel;

import java.util.List;
import model.MinMaxData;
import model.TestConnection;

/**
 *
 * @author rachmad
 */
public class AnalisaPanel extends javax.swing.JPanel {
    private String min, max;
    private MinMaxData minMaxData;
    private TestConnection tc;
    /**
     * Creates new form AnalisaPanel
     */
    public AnalisaPanel(String getModelName, Object columnName, Object columnData) {
        tc = new TestConnection();
        initComponents();
        
        lblModel.setText(getModelName);
        lblColumn.setText(columnName.toString());
        lblMax.setText("batas " + columnName.toString() + " max");
        lblMax2.setText("batas " + columnName.toString() + " max");
        lblMin.setText("batas " + columnName.toString() + " min");
        lblCurrent.setText(columnName.toString() + " mobil");
        
        minMaxData = new MinMaxData(tc.getConnection(), "utility", columnName.toString());
        max = minMaxData.getMax();
        min = minMaxData.getMin();
        txtMax.setText(max);
        txtMax2.setText(max);
        txtMin.setText(min);
        txtCurrent.setText(columnData.toString());
        
        double maxVal = Double.parseDouble(max);
        double minVal = Double.parseDouble(min);
        double currentVal = Double.parseDouble(columnData.toString());
        double result = ((maxVal - currentVal) / (maxVal - minVal));
        txtResult.setText(Double.toString(result * 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblColumn = new javax.swing.JLabel();
        lblMax = new javax.swing.JLabel();
        lblCurrent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMax2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCurrent = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtMax2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblModel = new javax.swing.JLabel();

        setLayout(null);

        lblColumn.setText("Bobot Harga =");
        add(lblColumn);
        lblColumn.setBounds(10, 50, 110, 16);

        lblMax.setText("Batas harga max");
        add(lblMax);
        lblMax.setBounds(120, 40, 200, 16);

        lblCurrent.setText("Harga mobil");
        add(lblCurrent);
        lblCurrent.setBounds(350, 40, 160, 16);

        jLabel1.setText("-");
        add(jLabel1);
        jLabel1.setBounds(330, 40, 10, 16);

        jSeparator1.setBackground(java.awt.Color.black);
        add(jSeparator1);
        jSeparator1.setBounds(110, 120, 280, 10);

        lblMax2.setText("Batas harga max");
        add(lblMax2);
        lblMax2.setBounds(120, 70, 200, 16);

        jLabel3.setText("-");
        add(jLabel3);
        jLabel3.setBounds(330, 70, 10, 16);

        lblMin.setText("Batas Harga min");
        add(lblMin);
        lblMin.setBounds(350, 70, 110, 16);

        txtMax.setEditable(false);
        txtMax.setText("728000000");
        add(txtMax);
        txtMax.setBounds(120, 130, 120, 20);

        jLabel5.setText("-");
        add(jLabel5);
        jLabel5.setBounds(250, 100, 10, 16);

        txtCurrent.setEditable(false);
        txtCurrent.setText("137400000");
        add(txtCurrent);
        txtCurrent.setBounds(270, 100, 110, 20);

        jSeparator2.setBackground(java.awt.Color.black);
        add(jSeparator2);
        jSeparator2.setBounds(110, 60, 280, 10);

        txtMax2.setEditable(false);
        txtMax2.setText("728000000");
        add(txtMax2);
        txtMax2.setBounds(120, 100, 120, 20);

        jLabel6.setText("-");
        add(jLabel6);
        jLabel6.setBounds(250, 130, 10, 16);

        txtMin.setEditable(false);
        txtMin.setText("137000000");
        add(txtMin);
        txtMin.setBounds(270, 130, 110, 20);

        jLabel7.setText("100%");
        add(jLabel7);
        jLabel7.setBounds(400, 110, 36, 16);

        jLabel8.setText("100%");
        add(jLabel8);
        jLabel8.setBounds(490, 50, 36, 16);

        txtResult.setEditable(false);
        txtResult.setText("99,93");
        add(txtResult);
        txtResult.setBounds(120, 160, 260, 26);

        jPanel2.setBackground(new java.awt.Color(175, 179, 251));

        lblModel.setText("Brio Satya");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(jPanel2);
        jPanel2.setBounds(0, 0, 560, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblColumn;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblMax;
    private javax.swing.JLabel lblMax2;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblModel;
    private javax.swing.JTextField txtCurrent;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMax2;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
