/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package design.client;

import design.DataMobil;
import design.InsertUpdate;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicComboBoxRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;
import model.ListData;
import model.LoadTable;
import model.MinMaxData;
import model.TestConnection;

/**
 *
 * @author rachmad
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private MinMaxData minMaxData;
    DefaultTableModel tm, currtableModel;
    TestConnection tc;
    List<JComboBox<String>> combo = new ArrayList<>();
    List<JTextField> txtListId = new ArrayList<>();
    List<JLabel> lblCombo = new ArrayList<>();
    Vector originalTableModel;
    String max;
    String budget = "";
    public MainForm() {
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        getRootPane().setWindowDecorationStyle(javax.swing.JRootPane.NONE);
        setLocation(0,0);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        
        tc = new TestConnection();
        tm = new LoadTable(tc.getConnection(), "select * from mobil").getTableModel();
        
        setSize((int)screenSize.getWidth()-50,(int)screenSize.getHeight()-50);
        
        /* combo list fot criteria */
        //Object[] dataModelMobil = new ListData("mobil", "model").getData();
        Object[] dataModelMultiColumn = new ListData("mobil", "id_mobil", "model").getMultiColumnData();
        for(int i=0; i<8; i++){
            JLabel lblComboBox = new JLabel("Alternatif " + (i+1) + "   ");
            
            /* set multi value inside combobox */
            Vector model = new Vector();
            for(int j=i; j<dataModelMultiColumn.length; j++){
                //System.out.println(Arrays.toString((String[])dataModelMultiColumn[j]));
                String[] dataMobil = (String[])dataModelMultiColumn[j];
                model.addElement(new Item(dataMobil[0], dataMobil[1]));
            }
            
            JComboBox comboBox = new JComboBox(model);
            JTextField textField = new JTextField();
            
            Item item = (Item)comboBox.getSelectedItem();
            textField.setText(item.getId());
//            comboBox.setRenderer( new ItemRenderer() );
            
            lblCombo.add(lblComboBox);
            combo.add(comboBox);
            txtListId.add(textField);
            
            comboBox.addItemListener(new java.awt.event.ItemListener() {
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    JComboBox comboBox = (JComboBox)evt.getSource();
                    Item item = (Item)comboBox.getSelectedItem();
                    //System.out.println( item.getId() + " : " + item.getDescription() );
                    textField.setText(item.getId());
                }
            });
        }
        
        initComponents();
        
        minMaxData = new MinMaxData(tc.getConnection(), "mobil", "purna_jual");
        max = minMaxData.getMax();
        
        originalTableModel = (Vector) ((DefaultTableModel) jTable2.getModel()).getDataVector().clone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtModel = new javax.swing.JTextField();
        txtTransmisi = new javax.swing.JTextField();
        txtWarna = new javax.swing.JTextField();
        txtKapasitas = new javax.swing.JTextField();
        txtBahanBakar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtPurnaJual = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chkTransmisi = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        chkWarna = new javax.swing.JCheckBox();
        chkKapasitas = new javax.swing.JCheckBox();
        chkBahanBakar = new javax.swing.JCheckBox();
        chkHarga = new javax.swing.JCheckBox();
        chkPurnaJual = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtBudget = new javax.swing.JTextField();
        jComboBox9 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        panelLabelLaternatif = new javax.swing.JPanel();
        panelAlternatif = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtModel1 = new javax.swing.JTextField();
        txtTransmisi1 = new javax.swing.JTextField();
        txtWarna1 = new javax.swing.JTextField();
        txtKapasitas1 = new javax.swing.JTextField();
        txtBahanBakar1 = new javax.swing.JTextField();
        txtHarga1 = new javax.swing.JTextField();
        txtPurnaJual1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtModelBobot1 = new javax.swing.JTextField();
        txtTransmisiBobot1 = new javax.swing.JTextField();
        txtWarnaBobot1 = new javax.swing.JTextField();
        txtKapasitasBobot1 = new javax.swing.JTextField();
        txtBahanBakarBobot1 = new javax.swing.JTextField();
        txtHargaBobo1 = new javax.swing.JTextField();
        txtPurnaJualBobot1 = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtModel3 = new javax.swing.JTextField();
        txtTransmisi3 = new javax.swing.JTextField();
        txtWarna3 = new javax.swing.JTextField();
        txtKapasitas3 = new javax.swing.JTextField();
        txtBahanBakar3 = new javax.swing.JTextField();
        txtHarga3 = new javax.swing.JTextField();
        txtPurnaJual3 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtModelBobot3 = new javax.swing.JTextField();
        txtTransmisiBobot3 = new javax.swing.JTextField();
        txtWarnaBobot3 = new javax.swing.JTextField();
        txtKapasitasBobot3 = new javax.swing.JTextField();
        txtBahanBakarBobot3 = new javax.swing.JTextField();
        txtHargaBobo3 = new javax.swing.JTextField();
        txtPurnaJualBobot3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(tm);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Baru");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 167, 167)));
        jPanel5.setToolTipText("");

        jLabel1.setText("Model");

        jLabel2.setText("Transmisi");

        jLabel3.setText("Warna");

        jLabel4.setText("Kapasitas");

        jLabel5.setText("Bahan Bakar");

        txtModel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModelKeyTyped(evt);
            }
        });

        jLabel6.setText("Harga");

        jLabel7.setText("Purna Jual");

        txtId.setVisible(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtModel)
                            .addComponent(txtTransmisi)
                            .addComponent(txtWarna)
                            .addComponent(txtKapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBahanBakar)
                            .addComponent(txtHarga)
                            .addComponent(txtPurnaJual, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBahanBakar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTransmisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWarna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtPurnaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1127, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Mobil", jPanel1);

        chkTransmisi.setSelected(true);
        chkTransmisi.setText("Transmisi");

        jLabel8.setText("Tentukan kriteria");

        chkWarna.setSelected(true);
        chkWarna.setText("Warna");

        chkKapasitas.setSelected(true);
        chkKapasitas.setText("Kapasitas");

        chkBahanBakar.setSelected(true);
        chkBahanBakar.setText("Bahan Bakar");

        chkHarga.setSelected(true);
        chkHarga.setText("Harga");

        chkPurnaJual.setSelected(true);
        chkPurnaJual.setText("Purna Jual");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkWarna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkKapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkBahanBakar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkPurnaJual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkTransmisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(1033, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkTransmisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkWarna)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkKapasitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBahanBakar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPurnaJual)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Kriteria", jPanel2);

        jLabel23.setText("Budget");

        jLabel24.setText("Jumlah yang di pilih");

        txtBudget.setDocument(new JTextFieldLimit(10));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBox9.setSelectedIndex(7);
        jComboBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox9ItemStateChanged(evt);
            }
        });

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel8.setLayout(new java.awt.BorderLayout());

        panelLabelLaternatif.setLayout(new java.awt.GridLayout(8, 0));
        for(int i=0; i<8; i++){
            panelLabelLaternatif.add(lblCombo.get(i));
        }
        jPanel8.add(panelLabelLaternatif, java.awt.BorderLayout.LINE_START);

        panelAlternatif.setBorder(null);
        panelAlternatif.setLayout(new java.awt.GridLayout(8, 0));

        for(int i=0; i<8; i++){
            panelAlternatif.add(combo.get(i));
        }

        jPanel8.add(panelAlternatif, java.awt.BorderLayout.CENTER);

        jTable2.setModel(tm);
        jScrollPane2.setViewportView(jTable2);

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jPanel11.setLayout(new java.awt.GridLayout(8, 0));
        for(int i=0; i<8; i++){
            jPanel11.add(txtListId.get(i));
        }

        jPanel11.setVisible(false);

        jLabel13.setText("Search   ");

        jButton5.setText("Proses");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(101, 101, 101)
                                .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24)
                                .addGap(25, 25, 25)
                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton5))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Alternatif", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBorder(null);
        jPanel9.setLayout(new java.awt.GridLayout(8, 0));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Kriteria Paling Tidak Penting");
        jPanel9.add(jLabel9);
        jPanel9.add(txtModel1);
        jPanel9.add(txtTransmisi1);
        jPanel9.add(txtWarna1);
        jPanel9.add(txtKapasitas1);
        jPanel9.add(txtBahanBakar1);
        jPanel9.add(txtHarga1);
        jPanel9.add(txtPurnaJual1);

        jPanel10.setBorder(null);
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        jPanel14.setLayout(new java.awt.GridLayout(8, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bobot");
        jPanel14.add(jLabel10);
        jPanel14.add(txtModelBobot1);
        jPanel14.add(txtTransmisiBobot1);
        jPanel14.add(txtWarnaBobot1);
        jPanel14.add(txtKapasitasBobot1);
        jPanel14.add(txtBahanBakarBobot1);
        jPanel14.add(txtHargaBobo1);
        jPanel14.add(txtPurnaJualBobot1);

        jPanel10.add(jPanel14);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel16.setBorder(null);
        jPanel16.setLayout(new java.awt.GridLayout(8, 0));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Kriteria Paling Tidak Penting");
        jPanel16.add(jLabel11);
        jPanel16.add(txtModel3);
        jPanel16.add(txtTransmisi3);
        jPanel16.add(txtWarna3);
        jPanel16.add(txtKapasitas3);
        jPanel16.add(txtBahanBakar3);
        jPanel16.add(txtHarga3);
        jPanel16.add(txtPurnaJual3);

        jPanel17.setBorder(null);
        jPanel17.setLayout(new java.awt.GridLayout(1, 0));

        jPanel18.setLayout(new java.awt.GridLayout(8, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Bobot");
        jPanel18.add(jLabel12);
        jPanel18.add(txtModelBobot3);
        jPanel18.add(txtTransmisiBobot3);
        jPanel18.add(txtWarnaBobot3);
        jPanel18.add(txtKapasitasBobot3);
        jPanel18.add(txtBahanBakarBobot3);
        jPanel18.add(txtHargaBobo3);
        jPanel18.add(txtPurnaJualBobot3);

        jPanel17.add(jPanel18);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Pembobotan Kriteria", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1151, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Hasil Keputusan", jPanel4);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        JTable table =(JTable) evt.getSource();
        java.awt.Point p = evt.getPoint();
        int selectedRowIndex = jTable1.getSelectedRow();
        String selectedObject = jTable1.getModel().getValueAt(selectedRowIndex, 2)+"";

        try{
            ArrayList<Object> dataValue = new ArrayList<Object>();
            int column = 0;
            int row = jTable1.getSelectedRow();
            txtId.setText(jTable1.getModel().getValueAt(row, 0).toString());
            txtModel.setText(jTable1.getModel().getValueAt(row, 1).toString());
            txtTransmisi.setText(jTable1.getModel().getValueAt(row, 2).toString());
            txtWarna.setText(jTable1.getModel().getValueAt(row, 3).toString());
            txtKapasitas.setText(jTable1.getModel().getValueAt(row, 4).toString());
            txtBahanBakar.setText(jTable1.getModel().getValueAt(row, 5).toString());
            txtHarga.setText(jTable1.getModel().getValueAt(row, 6).toString());
            txtPurnaJual.setText(jTable1.getModel().getValueAt(row, 7).toString());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new InsertUpdate(jTable1, 0).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            ArrayList<Object> dataValue = new ArrayList<Object>();
            int column = 0;
            int row = jTable1.getSelectedRow();
            for(int i = 0; i<jTable1.getColumnCount(); i++){
                dataValue.add(jTable1.getModel().getValueAt(row, i).toString());
            }
            
            Object[] data = new Object[dataValue.size()];
//            String value = jTable1.getModel().getValueAt(row, column).toString();
//            JOptionPane.showMessageDialog(null, dataValue);
            new InsertUpdate(jTable1, 1, dataValue.toArray(data)).setVisible(true);
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String getValue = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString();
            if(JOptionPane.showConfirmDialog(null, "Are you sure to delete data?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION){
                try {
                    Statement st = tc.getConnection().createStatement();
                    String sql = "DELETE FROM `mobil` WHERE id_mobil = '" + getValue + "'";
                    System.out.println(sql);
                    st.executeUpdate(sql);
                    st.close();

                    String query = "SELECT id_mobil, model, transmisi, warna, kapasitas, bahan_bakar, harga, purna_jual FROM mobil";
                    tc = new TestConnection();
                    tm = new LoadTable(tc.getConnection(), query).getTableModel();

                    jTable1.setModel(tm);
                } catch (SQLException ex) {
                    Logger.getLogger(DataMobil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox9ItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            for(int i=0; i<combo.size(); i++){
                int selected = Integer.parseInt(jComboBox9.getSelectedItem().toString());
                if(i < selected)
                    combo.get(i).setEnabled(true);
                else
                    combo.get(i).setEnabled(false);
            }
//            System.out.println(jComboBox9.getItemAt(jComboBox9.getSelectedIndex()) + " : " + jComboBox9.getSelectedItem());
        }
    }//GEN-LAST:event_jComboBox9ItemStateChanged

    private void txtModelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModelKeyTyped
        
    }//GEN-LAST:event_txtModelKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try{
            budget = txtBudget.getText();
            /* filter table */
            currtableModel = (DefaultTableModel) jTable2.getModel();
            //To empty the table before search
            currtableModel.setRowCount(0);
            //To search for contents from original table content
            for (Object rows : originalTableModel) {
                Vector rowVector = (Vector) rows;
                Object purnaJualColumn = rowVector.get(7);
                System.out.println(purnaJualColumn);
                if(!txtBudget.getText().equals("")){
                    if ((Integer.parseInt(purnaJualColumn.toString()) <= Integer.parseInt(txtBudget.getText()))) {
                        //content found so adding to table
                        currtableModel.addRow(rowVector);
                    }
                }
                else{
                    if ((Integer.parseInt(purnaJualColumn.toString()) <= Integer.parseInt(max))) {
                        currtableModel.addRow(rowVector);
                    }
                }
            }
            
            
            int budget = Integer.parseInt(txtBudget.getText());
            
//            Object sql = "select model from mobil where purna_jual <= " + budget + ";";
//            Object[] dataModelMobil = new ListData(sql, "model").getData();
//            for(int i=0; i<combo.size(); i++){
//                combo.get(i).removeAllItems();
//                if(dataModelMobil.length > 0){
//                    for(Object data : dataModelMobil)
//                        combo.get(i).addItem(data.toString());
//                }
//                else{
//                    combo.get(i).addItem("--Empty--");
//                }
//            }
            
            //Object sql = "select model from mobil where purna_jual <= " + budget + ";";
            Object[] dataModelMultiColumn = new ListData("mobil", "id_mobil", "model", budget).getMultiColumnData();
            System.out.println("Data Mobil : " + dataModelMultiColumn.length);
            
            if(dataModelMultiColumn.length < 8){
                DefaultComboBoxModel countItemDisable = new DefaultComboBoxModel();
                for(int k=0; k< dataModelMultiColumn.length; k++){
                    countItemDisable.addElement( k+1 );
                }
                jComboBox9.setModel(countItemDisable);
                jComboBox9.setSelectedIndex(dataModelMultiColumn.length - 1);
            }
            else{
                DefaultComboBoxModel countItemDisable = new DefaultComboBoxModel();
                for(int k=0; k< 8; k++){
                    countItemDisable.addElement( k+1 );
                }
                jComboBox9.setModel(countItemDisable);
                jComboBox9.setSelectedIndex(7);
            }
            
            for(int i=0; i<combo.size(); i++){
                try{
                    //combo.get(i).removeAllItems();
                    txtListId.get(i).setText("");
                    combo.get(i).setEnabled(true);
                    
                    Vector model = new Vector();
                    if(dataModelMultiColumn.length > 0){
                        /* set multi value inside combobox */
                        if(dataModelMultiColumn.length > 8){
                            for(int j=i; j<dataModelMultiColumn.length; j++){
                                //System.out.println(Arrays.toString((String[])dataModelMultiColumn[j]));
                                String[] dataMobil = (String[])dataModelMultiColumn[j];
                                model.addElement(new Item(dataMobil[0], dataMobil[1]));
                            }
                        }
                        else{
                            for(int j=i; j<8; j++){
                                //System.out.println(Arrays.toString((String[])dataModelMultiColumn[j]));
                                try{
                                    String[] dataMobil = (String[])dataModelMultiColumn[j];
                                    model.addElement(new Item(dataMobil[0], dataMobil[1]));
                                }
                                catch(ArrayIndexOutOfBoundsException e){
                                    /* if out of index item */
                                }
                            }
                        }
            //            comboBox.setRenderer( new ItemRenderer() );
                    }
                    else{
                        model.addElement(new Item("", "--Empty--"));
                    }

                    combo.get(i).setModel(new DefaultComboBoxModel(model));
                    //combo.get(i) = new JComboBox(model);
                    Item item = (Item)combo.get(i).getSelectedItem();
                    txtListId.get(i).setText(item.getId());
                }
                catch(NullPointerException ee){
                    /* if combo out of bound */
                    combo.get(i).setEnabled(false);
                }
            }
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        currtableModel = (DefaultTableModel) jTable2.getModel();
        //To empty the table before search
        currtableModel.setRowCount(0);
        //To search for contents from original table content
        for (Object rows : originalTableModel) {
            Vector rowVector = (Vector) rows;
            Object purnaJualColumn = rowVector.get(7);
            for (Object column : rowVector) {
                if(Pattern.compile("^\\s+$").matcher(budget).find() || budget.equals("")){
                    if (column.toString().toLowerCase().contains(txtSearch.getText())) {
                        //content found so adding to table
                        currtableModel.addRow(rowVector);
                        break;
                    }
                }
                else{
                    if (column.toString().toLowerCase().contains(txtSearch.getText()) && (Integer.parseInt(purnaJualColumn.toString()) <= Integer.parseInt(budget))) {
                        //content found so adding to table
                        currtableModel.addRow(rowVector);
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkBahanBakar;
    private javax.swing.JCheckBox chkHarga;
    private javax.swing.JCheckBox chkKapasitas;
    private javax.swing.JCheckBox chkPurnaJual;
    private javax.swing.JCheckBox chkTransmisi;
    private javax.swing.JCheckBox chkWarna;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelAlternatif;
    private javax.swing.JPanel panelLabelLaternatif;
    private javax.swing.JTextField txtBahanBakar;
    private javax.swing.JTextField txtBahanBakar1;
    private javax.swing.JTextField txtBahanBakar3;
    private javax.swing.JTextField txtBahanBakarBobot1;
    private javax.swing.JTextField txtBahanBakarBobot3;
    private javax.swing.JTextField txtBudget;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtHarga3;
    private javax.swing.JTextField txtHargaBobo1;
    private javax.swing.JTextField txtHargaBobo3;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtKapasitas1;
    private javax.swing.JTextField txtKapasitas3;
    private javax.swing.JTextField txtKapasitasBobot1;
    private javax.swing.JTextField txtKapasitasBobot3;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtModel1;
    private javax.swing.JTextField txtModel3;
    private javax.swing.JTextField txtModelBobot1;
    private javax.swing.JTextField txtModelBobot3;
    private javax.swing.JTextField txtPurnaJual;
    private javax.swing.JTextField txtPurnaJual1;
    private javax.swing.JTextField txtPurnaJual3;
    private javax.swing.JTextField txtPurnaJualBobot1;
    private javax.swing.JTextField txtPurnaJualBobot3;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTransmisi;
    private javax.swing.JTextField txtTransmisi1;
    private javax.swing.JTextField txtTransmisi3;
    private javax.swing.JTextField txtTransmisiBobot1;
    private javax.swing.JTextField txtTransmisiBobot3;
    private javax.swing.JTextField txtWarna;
    private javax.swing.JTextField txtWarna1;
    private javax.swing.JTextField txtWarna3;
    private javax.swing.JTextField txtWarnaBobot1;
    private javax.swing.JTextField txtWarnaBobot3;
    // End of variables declaration//GEN-END:variables
}

class JTextFieldLimit extends PlainDocument {
    private int limit;

    JTextFieldLimit(int limit) {
     super();
     this.limit = limit;
     }

    public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
        if (str == null) return;

        if ((getLength() + str.length()) <= limit) {
          super.insertString(offset, str, attr);
        }
    }
}

class Item
{
    private String id;
    private String description;

    public Item(String id, String description)
    {
        this.id = id;
        this.description = description;
    }

    public String getId()
    {
        return id;
    }

    public String getDescription()
    {
        return description;
    }

    public String toString()
    {
        return description;
    }
}

class ItemRenderer extends BasicComboBoxRenderer
{
    public Component getListCellRendererComponent(
        JList list, Object value, int index,
        boolean isSelected, boolean cellHasFocus){
        super.getListCellRendererComponent(list, value, index,
            isSelected, cellHasFocus);

        if (value != null)
        {
            Item item = (Item)value;
            setText( item.getDescription().toUpperCase() );
        }

        if (index == -1)
        {
            Item item = (Item)value;
            setText( "" + item.getId() );
        }


        return this;
    }
}
